/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author paulo
 */
public class jifListagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifListagem
     */
    public jifListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jcTodos = new javax.swing.JCheckBox();
        jcAtivos = new javax.swing.JCheckBox();
        jcInativos = new javax.swing.JCheckBox();
        jbImprimir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Listagem de Contatos");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        buttonGroup1.add(jcTodos);
        jcTodos.setText("Todos");
        jcTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTodosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jcAtivos);
        jcAtivos.setText("Ativos");

        buttonGroup1.add(jcInativos);
        jcInativos.setText("Inativos");

        jbImprimir.setText("Imprimir");
        jbImprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcTodos)
                        .addGap(37, 37, 37)
                        .addComponent(jcAtivos)
                        .addGap(41, 41, 41)
                        .addComponent(jcInativos)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcAtivos)
                    .addComponent(jcTodos)
                    .addComponent(jcInativos))
                .addGap(18, 18, 18)
                .addComponent(jbImprimir)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setBounds(600, 250, 318, 146);
    }// </editor-fold>//GEN-END:initComponents

    private void jcTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTodosActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        jcAtivos.setSelected(true);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jbImprimir;
    private javax.swing.JCheckBox jcAtivos;
    private javax.swing.JCheckBox jcInativos;
    private javax.swing.JCheckBox jcTodos;
    // End of variables declaration//GEN-END:variables
}
